export const SUBREDDITS_REQUEST = 'SUBREDDITS_REQUEST';
export const SUBREDDITS_SUCCESS = 'SUBREDDITS_SUCCESS';
export const SUBREDDITS_FAILURE = 'SUBREDDITS_FAILURE';

export const SUBREDDIT_REQUEST = 'SUBREDDIT_REQUEST';
export const SUBREDDIT_SUCCESS = 'SUBREDDIT_SUCCESS';
export const SUBREDDIT_FAILURE = 'SUBREDDIT_FAILURE';

export const SUBREDDIT_FILTER = 'SUBREDDIT_FILTER';

export const SUBREDDIT_NEW_REQUEST = 'SUBREDDIT_NEW_REQUEST';
export const SUBREDDIT_NEW_SUCCESS = 'SUBREDDIT_NEW_SUCCESS';
export const SUBREDDIT_NEW_FAILURE = 'SUBREDDIT_NEW_FAILURE';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';
