export const SUBREDDITS_REQUEST = 'SUBREDDITS_REQUEST';
export const SUBREDDITS_SUCCESS = 'SUBREDDITS_SUCCESS';
export const SUBREDDITS_FAILURE = 'SUBREDDITS_FAILURE';

export const SUBREDDIT_REQUEST = 'SUBREDDIT_REQUEST';
export const SUBREDDIT_SUCCESS = 'SUBREDDIT_SUCCESS';
export const SUBREDDIT_FAILURE = 'SUBREDDIT_FAILURE';

export const SUBREDDIT_FILTER = 'SUBREDDIT_FILTER';
